[workspace]
[package]
name = "simple-signature"
version = "0.1.0"
edition = "2021"

[dependencies]
sphinx-zkvm = { path = "../../../zkvm/entrypoint" }

bls12_381 = { git = "https://github.com/argumentcomputer/bls12_381", branch = "zkvm" }
